name: Bug Report
description: Report a bug in the project
title: "[BUG] "
labels: bug
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        **Describe the bug**
        A clear and concise description of what the bug is.

  - type: input
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: input
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What you expected to happen
    validations:
      required: true

  - type: input
    id: screenshots
    attributes:
      label: Screenshots
      placeholder: Add screenshots if applicable
