name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: enhancement
assignees: ''

body:
  - type: input
    id: feature
    attributes:
      label: Feature Description
      placeholder: Describe the feature or enhancement you want
    validations:
      required: true

  - type: input
    id: motivation
    attributes:
      label: Motivation
      placeholder: Why this feature is needed or useful
    validations:
      required: true

  - type: input
    id: screenshots
    attributes:
      label: Screenshots or Mockups
      placeholder: Add screenshots or mockups if applicable
